version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: app/frontend/Dockerfile
    ports:
      - "80:80"
    environment:
      - VITE_API_URL=http://backend:5000
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: .
      dockerfile: app/backend/Dockerfile
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGODB_URI=mongodb://user_iiprofit:499%23Waterloo@mongodb:27017/adminsyncDB?authSource=adminsyncDB
    depends_on:
      - mongodb
    networks:
      - app-network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./app/backend/scripts/init-mongodb.sh:/docker-entrypoint-initdb.d/init-mongodb.sh
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin123
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data: 